spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:10101/bluo_resource?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
minio:
  url: http://127.0.0.1:19000
  username: root
  password: root