server:
  port: 30002
mybatis-plus:
  global-config:
    banner: off

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:10101/bluo_resource?serverTimezone=Asia/Shanghai
  main:
    banner-mode: off
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss #时间戳统一转换为指定格式
      time-zone: GMT+8 # 时区修改为东8 区